### PR TITLE
Merge updated tests & test-tooling into develop

### PR DESCRIPTION
**Pull request by damienomurchu**
Based on several JIRAs all centering around the addition of unit tests and testing-related tooling to data-miner:

- https://issues.jboss.org/browse/FH-3504
- https://issues.jboss.org/browse/FH-3505
- https://issues.jboss.org/browse/FH-3506
- https://issues.jboss.org/browse/FH-3507
- https://issues.jboss.org/browse/FH-3538
- https://issues.jboss.org/browse/FH-3548

Work almost complete, but very small number of tests still to add.

@austincunningham feel free to take a look if you want to review it now. All tests in place bar 3/ 4 small tests in data-spec.js, which I'll implement the next pass I take at this. 98% of tests in place otherwise

### CODE REVIEW

**Comment by austincunningham** [comment]
Need to pull the repo and run the tests before approving, also presume that the NPM has been updated? if so will need to test with Kujira to approve.

**Comment by austincunningham** [comment]
# Error when running tests from branch testing
````"C:\Program Files (x86)\JetBrains\WebStorm 2016.2.3\bin\runnerw.exe" "C:\Program Files\nodejs\node.exe" C:\Users\austin\redhat-repo\data-miner\tests\utils\sprintReport-spec.js
C:\Users\austin\redhat-repo\data-miner\tests\utils\sprintReport-spec.js:9
describe('SprintReport tests', function () {
^

ReferenceError: describe is not defined
    at Object.<anonymous> (C:\Users\austin\redhat-repo\data-miner\tests\utils\sprintReport-spec.js:9:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

Process finished with exit code 1````

**Comment by damienomurchu** [comment]
All tests fully implemented now. To test:

- pull the code
- check out the testing branch
- run `npm install` in a terminal 
- run the command `npm test`  or `npm run-script test-travis` (this latter command runs the tests & gives the test coverage % too)

(reason your tests failed before is your webstorm setup - I have no control over that, but the tests will run from the commandline above, and that is how Travis, Istanbul & Coveralls are implemented too)

**Comment by damienomurchu** [comment]
No changes have been made to the npm package as this isn't merged code yet

**Comment by austincunningham** [comment]
data-miner-testing

**Comment by damienomurchu** [comment]
all tests passing when run from the terminal with `npm test` above - could you verify they are for you too (passing from an `npm test` in the terminal)

**Comment by austincunningham** [comment]
````austin@Lap-austin MINGW64 ~/redhat-repo/data-miner (testing)
$ npm test

> kujira-data-miner@0.3.0-alpha.7 test C:\Users\austin\redhat-repo\data-miner
> mocha -u tdd --recursive --reporter spec '**/*spec.js'

Warning: Could not find any test files matching pattern: '**/*spec.js'
No test files found
npm ERR! Test failed.  See above for more details.````

# More than likely a path issue.

**Pull request merged**
